### ISSUE TITLE
IE8+ Support

### ISSUE THREAD

**Issue by mattjcowan** [ServiceStackApps/Chat#1]
Would be nice to get this sample to work in IE out of the gates (even IE8+). I created a fork and was able to do it pretty quickly, by doing the following (even though these are loosely covered in ServiceStack docs, it might be nice to get the sample running without issues for everyone). Most of my clients require IE support, and many still require IE8+.

Could even just create a separate page in the demo (like default_ie8plus.cshtml).
Granted I was only using IE8, IE9, IE10 emulation in my tests, but without supporting these browsers, I would not have been able to convince my client that using this was a viable option, and that would have been a shame :-)

Here's what I did:

1) Added bower and installed the following libraries:
     - jquery version 1.11.2: for lte IE9 support (instead of using jquery 2x)
     - console-polyfill: for lte IE9 support (the Yaffle polyfill throws exceptions in IE in certain cases without this)
     - es5-shim: for lte IE8 support
     - event-source-polyfill: Yaffle polyfill (for IE support)

2) Added the script tags to the default.cshtml in the following order

```
<link href="/default.css" rel="stylesheet" />
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<!-- need the following item for lte IE9 -->
<script src="/bower_components/console-polyfill/index.js"></script>
<!-- need the following item for lte IE8 -->
<script src="/bower_components/es5-shim/es5-shim.min.js"></script>
<script src="/bower_components/event-source-polyfill/eventsource.min.js"></script>
<script src="/js/ss-utils.js"></script>
```

3) Added the following config in the web.config to support running the app from Visual Studio without the horrible buffering delay:

```
<urlCompression doStaticCompression="true" doDynamicCompression="false" />
```

I believe that's it ... If you prefer to keep this out of the code-base, then maybe linking to a blog post with a working solution, or to a doc. Anyway, just a thought, feel free to close the issue.

**Comment by mythz** [comment]
Hi Matt, I'd be happy to accept a pull request that supports IE in a different file called something like `default_ieshim.html`.

**Comment by mattjcowan** [comment]
Ok, sounds good.
