### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ristaloff** [ServiceStackApps/Chat#4]
"Live Chat Example" link is broken on https://github.com/ServiceStackApps/Chat and https://github.com/ServiceStack/ServiceStack/wiki/Server-Events.
I'm not sure excatly what page it was supposed to point to.

**Comment by Layoric** [comment]
Thanks for reporting. 

Links are updated. They are support to point to [here](http://chat.servicestack.net/default_ieshim) but were just missing 'http://'.

Cheers! :+1:
